### PR TITLE
Add new target 'static' for building static distribution

### PR DESCRIPTION
**Pull request by fix-fix**
### Rationale

Since this package serves as a base for building apps on both server and client (e.g. universal React apps), it should be possible not only to run resulting apps with node server, which renders app content, but also to just serve them as static files.

For such apps where server-side handling is not critical, static builds add the possibility of deployment to static site hosting without server infrastructure, like github pages, and make them fully utilize CDN features.

This change will make it possible to build static distribution of SPA, i.e. distribution that can be served by a static server and doesn't require running app bundle from 'node' target.

See rocjs/roc-package-web-app-react#63 for previous implementation attempt

---

### Changes

There will be new possible target for `roc build` command: `static`. It reuses config from the `node` target, but entry script for `static` is expected to export a rendering function as default, that will be used to build static HTML documents with the help from `static-site-generator-webpack-plugin`.

I added an example of rendering of static distribution to `react` example and adjusted its minimum dependencies versions to fix missing validators errors.

Corresponding required changes to related extensions:

- [ ] rocjs/roc-package-web-app-react#64
- [ ] rocjs/roc-package-webpack-node#12
- [ ] rocjs/roc-plugin-style-css#12

### CODE REVIEW

**Comment by fix-fix** [comment]
Sidenotes and remaining problems:

1. How to document the new build target (usage, description, etc.)? It's not enabled by default and it won't be easy to discover this feature. Could it be moved to a plugin, if it's strongly dependent on some other package (roc-package-web-app)?
2. Building static distribution requires sequential execution of two commands (`roc build web && roc build static`), because static build process is relying on output of web build, so we can't run `roc build web,static`. It makes it more error-prone and harder to use. Do you have any idea about how to simplify this build process?
3. Rendering of React apps has't been switched to `renderToStaticMarkup`, because that package is still intented for full-blown SPAs with client-side routing, so there will be no gain from static markup and it's outside of scope of this change.
4. Errors inside 'static' output bundle occurred during **static-site-generator-webpack-plugin** rendering don't propagate to the outside build flow and don't stop it. I haven't figured out the cause of this.
5. List of node targets in [webpack config](https://github.com/fix-fix/roc-package-web-app/blob/8fc32c1fee4c06fd7830e359ad13c2db12e2fbf0/extensions/roc-package-web-app-dev/src/webpack/index.js) is hardcoded, because hook of getting list of node targets is defined in another package and `invokeHook` fails with an error. Is it ok to call `runHook` on hook from one package in another package? Or should the list be provided in a different way?

**Comment by dlmr** [comment]
This PR and the related ones have not been forgotten, thanks a lot for all the work and thought you have put into this!

The last couple of weeks has been extra hectic on both a personal and a professional level and this has unfortunately prevented me from giving this the love it rightfully deserves. 

Most of these "problems" have now been addressed and I will soon get back to this and I hope that this has not caused any issues for you.

**Comment by fix-fix** [comment]
Thanks for your feedback.

At my workplace we are currently trying to create a web projects development pipeline based on Roc, and while we're surely waiting for this feature, it doesn't cause any issues at the moment, since we can use the previous prototype made for React package with upgrading it later to the new version.

If there are possible improvements for general use of this feature or any other suggestions left to make it initial viable version, I'd like to hear them.

**Comment by fix-fix** [comment]
Is there any news on acceptance of this feature?

**Pull request closed without merging**
